class Solution:
    def groupAnagrams(self, strs: List[str]) -> List[List[str]]:
        # make a key that is generated by any anagram
        ans = collections.defaultdict(list) # map with universalKey and array of anagram strings

        for s in strs:
            uKey = [0] * 26
            for c in s:
                uKey[ord(c) - ord("a")] += 1
            
            ans[tuple(uKey)].append(s)
        
        return ans.values()

